apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "brainboard-runner.labels" . | nindent 4 }}
  name: {{ template "brainboard-runner.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
data:
  config.yaml: |-
    level: {{ .Values.config.logLevel }}

    runner:
      name: {{ .Values.config.name }}
      concurrency: {{ .Values.config.concurrency }}
      poll_interval: {{ .Values.config.poll_interval }}
      {{- if .Values.config.job_max_execution_time }}
      job_max_execution_time: {{ .Values.config.job_max_execution_time }}
      {{- end }}
      max_job_wait_time: {{ .Values.config.max_job_wait_time }}

    api:
      endpoint: {{ .Values.config.api.endpoint }}

    docker:
      registry: "{{ .Values.config.plugins.registry }}"
      shared_volume_path: "/secrets"
      ecr_auth: {{ if .Values.config.plugins.ecr.enabled }}true{{ else }}false{{ end }}
      {{- if .Values.config.plugins.ecr.enabled }}
      ecr_region: {{ .Values.config.plugins.ecr.aws_region }}
      {{ end }}
