{{ if .Values.warmup.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "brainboard-runner.fullname" . }}-warmup-config
  namespace: {{ .Release.Namespace }}
data:
  warmup.sh: |-
    #!/usr/bin/env sh
  
    # wait for docker daemon to be ready
    while [ ! -f /certs/client/ca.pem ]
    do
    echo "waiting for docker daemon to be ready"
    sleep 2
    done
    {{ $registry := .Values.config.plugins.registry }}
    {{- range .Values.config.plugins.list }}
    docker pull "{{ $registry }}/{{ .name }}:{{ .version }}"
    {{- end }}

    echo "finished pulling plugins docker images"
  
    while true
    do
    tail -f /dev/null & wait ${!}
    done
    {{- end }}